### ISSUE TITLE
command mode may not get repainted, causing CursorLineNr to not update

### ISSUE THREAD

**Issue by cameronr** [sethen/line-number-change-mode.nvim#4]
Whether the `redraw` is necessary likely depends on if something else is forcing a redraw statuscolumn already or not.

For example, this is my config with cmp doing cmdline completion. Apparently, it's not repainting the statuscolumn when I press `:` but does when I type the next character:
![with cmp](https://github.com/user-attachments/assets/bfcdc390-9795-4950-be18-ff870e5c7ca5)

And this is my config using no cmdline completion (cmp disabled). It doesn't repaint the statuscolumn ever so the wrong highlight for CursorLineNr is displayed the whole time:
![without cmp](https://github.com/user-attachments/assets/09ff8e40-c566-4a8b-af52-2e5bc2436043)

It may work for some config/themes that are already repainting but it won't work for configs that aren't repainting the statuscolumn.

Adding the redraw for `mode == 'c'` back in fixes it so I think that redraw is still necessary to make command mode work in all cases, particularly in configs that aren't already repainting the statuscolumn.

**Comment by sethen** [comment]
I am just wondering why this is breaking for you but not for me?

**Comment by sethen** [comment]
Also curious if this is specific to your setup?  Have you tried a clean install?

**Comment by cameronr** [comment]
> I am just wondering why this is breaking for you but not for me?

I looked at your config files. It's working for you because you're using `noice`. If you disable it, you'll see the problem in your config as well.

**Comment by sethen** [comment]
@cameronr Thanks!  I merged the fix.
